# This file is auto-generated by generate.sh.
# Edit child-specs.nix instead and run ./generate.sh.

{
  description = "Dynamic flake collection – single source of truth";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-26.05";
    flake-utils.url = "github:numtide/flake-utils";
    podman = { url = "./shells/podman"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    mariadb = { url = "./shells/mariadb"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    postgredb = { url = "./shells/postgredb"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    android-emulator = { url = "./shells/android-emulator"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    flutter-android = { url = "./shells/flutter-android"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    rust-minimal = { url = "./shells/rust-minimal"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    java25-maven = { url = "./shells/java25-maven"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
    java25-gradle = { url = "./shells/java25-gradle"; inputs = { nixpkgs.follows = "nixpkgs"; flake-utils.follows = "flake-utils"; }; };
  };
  outputs = { self, flake-utils, ... }@inputs:
    let
      childSpecs = import ./child-specs.nix;
      children = map (spec: { name = spec.name; flake = inputs.${spec.name}; }) childSpecs;
      getDefault = name: attr: system:
        let child = (builtins.head (builtins.filter (c: c.name == name) children)).flake or null;
        in if child == null then null
           else if child ? ${attr} && child.${attr} ? ${system} && child.${attr}.${system} ? default
           then child.${attr}.${system}.default
           else null;
      mkMerged = attr: system:
        builtins.listToAttrs (builtins.filter (x: x.value != null)
          (map (c: { name = c.name; value = getDefault c.name attr system; }) children));
      mergeAll = attr: system:
        builtins.foldl' (acc: child:
          if child.flake ? ${attr} && child.flake.${attr} ? ${system}
          then acc // child.flake.${attr}.${system}
          else acc
        ) { } children;
    in {
      devShells = builtins.listToAttrs (map (system: {
        name = system;
        value = mkMerged "devShells" system;
      }) flake-utils.lib.defaultSystems);
      apps = builtins.listToAttrs (map (system: {
        name = system;
        value = mergeAll "apps" system;
      }) flake-utils.lib.defaultSystems);
      packages = builtins.listToAttrs (map (system: {
        name = system;
        value = mergeAll "packages" system;
      }) flake-utils.lib.defaultSystems);
    };
}
